name: iptv_app
description: A professional IPTV application.
publish_to: 'none'
version: 1.0.0+1009

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^8.2.1
  cupertino_icons: ^1.0.2
  video_player: ^2.13.0
  media_kit: ^1.1.10
  media_kit_video: ^2.0.1
  media_kit_libs_windows_video: ^1.0.11
  media_kit_libs_macos_video: ^1.0.7
  media_kit_libs_android_video: ^1.0.7
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.1.0
  path_provider: ^2.1.1
  uuid: ^4.5.3
  flutter_secure_storage: ^11.0.0
  qr_flutter: ^4.1.0
  flutter_vlc_player: ^7.4.4
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  macos:
    generate: true
    image_path: "assets/icon.png"
  image_path: "assets/icon.png"
